// Generated by scripts/generate-tt-scrap-types.ts. Do not edit manually.
export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live
         * @description Report whether the process can serve HTTP requests.
         */
        get: operations["getHealthLive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Report whether required configuration is present.
         */
        get: operations["getHealthReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tiktok/extractions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Tiktok
         * @description Extract a TikTok post and return short-lived opaque asset references.
         */
        post: operations["extractTikTok"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tiktok/music": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Tiktok Music
         * @description Extract the music attached to a TikTok post by numeric post ID.
         */
        post: operations["extractTikTokMusic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tiktok/telegram-deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deliver Tiktok To Telegram
         * @description Resolve, prepare, and upload TikTok media using the server's Telegram bot.
         *
         *     `media` sends videos with metadata or slideshows as photo galleries;
         *     `document` sends original/file media without Telegram technical metadata; and
         *     `audio` sends the post's music. The caller supplies destination and optional
         *     Telegram parameters, but never multipart media fields or a bot token.
         *
         *     A single Telegram call is returned byte-for-byte with Telegram's HTTP status.
         *     Multiple gallery batches use `TelegramMultiDeliveryResponse`; HTTP 207 means an
         *     earlier batch succeeded before a later one failed. Do not blindly retry the
         *     whole request after timeouts or ambiguous upload failures because that can
         *     duplicate messages.
         */
        post: operations["deliverTikTokToTelegram"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/instagram/extractions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Instagram
         * @description Extract an Instagram post into ordered opaque media and thumbnail references.
         */
        post: operations["extractInstagram"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assets/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Asset
         * @description Download an opaque asset URL returned by an extraction response.
         *
         *     Send the same tt-scrap bearer token used for extraction. The token is temporary;
         *     download before the descriptor's `expires_at`. For TikTok adaptive video, this
         *     request also downloads the separate audio and performs a stream-copy MP4 mux
         *     before responding, so the downloaded video is playable and contains audio.
         */
        get: operations["downloadAsset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssetDescriptor
         * @description Temporary opaque reference to media that tt-scrap can download on demand.
         */
        AssetDescriptor: {
            /**
             * Asset Id
             * @description Opaque asset token; do not parse or persist it
             */
            asset_id: string;
            /**
             * Kind
             * @description Logical purpose of this asset
             * @enum {string}
             */
            kind: "video" | "image" | "audio" | "cover" | "thumbnail";
            /**
             * Position
             * @description Zero-based order within the post
             * @default 0
             */
            position: number;
            /**
             * Download Url
             * @description Relative authenticated download path. Resolve against the tt-scrap base URL
             */
            download_url: string;
            /**
             * Filename
             * @description Suggested filename before final format detection
             */
            filename: string;
            /**
             * Content Type
             * @description Declared MIME type when known; trust the download response type
             */
            content_type?: string | null;
            /**
             * Expires At
             * Format: date-time
             * @description Expiry time for this asset reference
             */
            expires_at: string;
        };
        /**
         * ErrorDetail
         * @description Stable machine-readable error details.
         */
        ErrorDetail: {
            /**
             * Code
             * @description Stable error identifier suitable for branching
             */
            code: string;
            /**
             * Message
             * @description Human-readable diagnostic; wording may change
             */
            message: string;
            /**
             * Request Id
             * @description Correlation ID to retain for logs and support
             */
            request_id: string;
        };
        /**
         * ErrorResponse
         * @description Error envelope returned by tt-scrap exception handlers.
         */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /**
         * InstagramExtractionRequest
         * @description Extract metadata and assets from an Instagram post URL.
         * @example {
         *       "refresh": false,
         *       "url": "https://www.instagram.com/reel/SHORTCODE/"
         *     }
         */
        InstagramExtractionRequest: {
            /**
             * Url
             * Format: uri
             */
            url: string;
            /**
             * Refresh
             * @default false
             */
            refresh: boolean;
        };
        /**
         * InstagramExtractionResponse
         * @description Normalized Instagram post information and temporary asset references.
         */
        InstagramExtractionResponse: {
            /** Extraction Id */
            extraction_id: string;
            /**
             * Platform
             * @default instagram
             * @constant
             */
            platform: "instagram";
            /** Source Url */
            source_url: string;
            /**
             * Content Type
             * @enum {string}
             */
            content_type: "video" | "image" | "carousel";
            /** Media */
            media: components["schemas"]["InstagramMediaItem"][];
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * InstagramMediaItem
         * @description One ordered Instagram media item with an optional thumbnail.
         */
        InstagramMediaItem: {
            /** Position */
            position: number;
            /**
             * Media Type
             * @enum {string}
             */
            media_type: "video" | "image";
            /** Quality */
            quality?: string | null;
            asset: components["schemas"]["AssetDescriptor"];
            thumbnail?: components["schemas"]["AssetDescriptor"] | null;
        };
        /** LiveResponse */
        LiveResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** ReadyResponse */
        ReadyResponse: {
            /**
             * Status
             * @default ready
             * @constant
             */
            status: "ready";
        };
        /**
         * TelegramAPIResponse
         * @description Raw response envelope returned by the Telegram Bot API.
         */
        TelegramAPIResponse: {
            /** Ok */
            ok: boolean;
            /** Result */
            result?: unknown | null;
            /** Error Code */
            error_code?: number | null;
            /** Description */
            description?: string | null;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * TelegramDeliveryRecord
         * @description One attempted Telegram album batch in delivery order.
         */
        TelegramDeliveryRecord: {
            /** Method */
            method: string;
            /** Status Code */
            status_code: number;
            /** Response */
            response: {
                [key: string]: unknown;
            } | unknown[] | string | null;
        };
        /**
         * TelegramMultiDeliveryResponse
         * @description Result used when a slideshow requires multiple Telegram album calls.
         */
        TelegramMultiDeliveryResponse: {
            /** Ok */
            ok: boolean;
            /** Partial */
            partial: boolean;
            /** Deliveries */
            deliveries: components["schemas"]["TelegramDeliveryRecord"][];
        };
        /**
         * TelegramParameters
         * @description Destination and caller-controlled Telegram Bot API parameters.
         *
         *     Extra Telegram fields are forwarded when compatible with the selected method.
         *     tt-scrap owns all multipart media fields, so callers must not supply `video`,
         *     `audio`, `photo`, `document`, `media`, `thumbnail`, or `cover`. Fields supported
         *     by one Telegram method can be rejected for another delivery/media combination.
         */
        TelegramParameters: {
            /**
             * Chat Id
             * @description Target chat ID or @channelusername accepted by the configured bot
             */
            chat_id: number | string;
            /** Business Connection Id */
            business_connection_id?: string | null;
            /** Message Thread Id */
            message_thread_id?: number | null;
            /** Direct Messages Topic Id */
            direct_messages_topic_id?: number | null;
            /** Receiver User Id */
            receiver_user_id?: number | null;
            /** Callback Query Id */
            callback_query_id?: string | null;
            /** Duration */
            duration?: number | null;
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
            /** Start Timestamp */
            start_timestamp?: number | null;
            /**
             * Caption
             * @description Caption for video/document/audio calls; not slideshow deliveries
             */
            caption?: string | null;
            /** Parse Mode */
            parse_mode?: string | null;
            /** Caption Entities */
            caption_entities?: {
                [key: string]: unknown;
            }[] | null;
            /** Show Caption Above Media */
            show_caption_above_media?: boolean | null;
            /** Has Spoiler */
            has_spoiler?: boolean | null;
            /** Supports Streaming */
            supports_streaming?: boolean | null;
            /** Disable Content Type Detection */
            disable_content_type_detection?: boolean | null;
            /** Performer */
            performer?: string | null;
            /** Title */
            title?: string | null;
            /** Disable Notification */
            disable_notification?: boolean | null;
            /** Protect Content */
            protect_content?: boolean | null;
            /** Allow Paid Broadcast */
            allow_paid_broadcast?: boolean | null;
            /** Message Effect Id */
            message_effect_id?: string | null;
            /** Suggested Post Parameters */
            suggested_post_parameters?: {
                [key: string]: unknown;
            } | null;
            /** Reply Parameters */
            reply_parameters?: {
                [key: string]: unknown;
            } | null;
            /** Reply Markup */
            reply_markup?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * TikTokExtractionRequest
         * @description Extract metadata and temporary asset references from a TikTok URL.
         * @example {
         *       "refresh": false,
         *       "url": "https://www.tiktok.com/@creator/video/1234567890123456789"
         *     }
         */
        TikTokExtractionRequest: {
            /**
             * Url
             * Format: uri
             * @description Public TikTok video, slideshow, or short URL
             */
            url: string;
            /**
             * Refresh
             * @description Bypass the short metadata cache and create a new extraction
             * @default false
             */
            refresh: boolean;
        };
        /**
         * TikTokExtractionResponse
         * @description Normalized TikTok post information with no upstream CDN URLs exposed.
         */
        TikTokExtractionResponse: {
            /**
             * Extraction Id
             * @description Short-lived extraction reference reusable by Telegram delivery; default TTL 60s
             */
            extraction_id: string;
            /**
             * Platform
             * @default tiktok
             * @constant
             */
            platform: "tiktok";
            /** Source Id */
            source_id: string;
            /** Source Url */
            source_url: string;
            /** Resolved Url */
            resolved_url: string;
            /**
             * Content Type
             * @description Determines whether media contains one video or ordered slideshow images
             * @enum {string}
             */
            content_type: "video" | "slideshow";
            cover?: components["schemas"]["AssetDescriptor"] | null;
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Likes */
            likes?: number | null;
            /** Views */
            views?: number | null;
            /**
             * Media
             * @description One selected best-quality video or ordered slideshow images
             */
            media: components["schemas"]["AssetDescriptor"][];
            music?: components["schemas"]["TikTokMusicMetadata"] | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * TikTokMusicMetadata
         * @description Music information embedded in a TikTok extraction response.
         */
        TikTokMusicMetadata: {
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Duration Seconds */
            duration_seconds: number;
            cover?: components["schemas"]["AssetDescriptor"] | null;
            audio?: components["schemas"]["AssetDescriptor"] | null;
        };
        /**
         * TikTokMusicRequest
         * @description Extract TikTok music using a numeric post ID.
         * @example {
         *       "video_id": 1234567890123456800
         *     }
         */
        TikTokMusicRequest: {
            /**
             * Video Id
             * @description Numeric TikTok post ID
             */
            video_id: number;
        };
        /**
         * TikTokMusicResponse
         * @description TikTok music metadata and temporary audio/cover asset references.
         */
        TikTokMusicResponse: {
            /** Extraction Id */
            extraction_id: string;
            /**
             * Platform
             * @default tiktok
             * @constant
             */
            platform: "tiktok";
            /** Source Id */
            source_id: string;
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Duration Seconds */
            duration_seconds: number;
            cover?: components["schemas"]["AssetDescriptor"] | null;
            audio: components["schemas"]["AssetDescriptor"];
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * TikTokTelegramDeliveryRequest
         * @description Request server-side TikTok preparation and direct Telegram upload.
         *
         *     The Telegram bot token is server configuration, not part of this request.
         *     `refresh` cannot be used with `source.extraction_id`.
         * @example {
         *       "delivery": "media",
         *       "refresh": false,
         *       "source": {
         *         "url": "https://www.tiktok.com/@creator/video/1234567890123456789"
         *       },
         *       "telegram": {
         *         "caption": "Optional caption",
         *         "chat_id": 123456789
         *       }
         *     }
         * @example {
         *       "delivery": "document",
         *       "source": {
         *         "extraction_id": "recent-extraction-id"
         *       },
         *       "telegram": {
         *         "chat_id": 123456789
         *       }
         *     }
         * @example {
         *       "delivery": "audio",
         *       "source": {
         *         "video_id": 1234567890123456800
         *       },
         *       "telegram": {
         *         "chat_id": 123456789
         *       }
         *     }
         */
        TikTokTelegramDeliveryRequest: {
            /** @description Exactly one TikTok source selector */
            source: components["schemas"]["TikTokTelegramSource"];
            /**
             * Delivery
             * @description media sends playable media/galleries; document sends files; audio sends music
             * @default media
             * @enum {string}
             */
            delivery: "media" | "document" | "audio";
            /**
             * Refresh
             * @description Bypass cached URL extraction; invalid with source.extraction_id
             * @default false
             */
            refresh: boolean;
            /** @description Telegram destination and optional method-compatible overrides */
            telegram: components["schemas"]["TelegramParameters"];
        };
        /**
         * TikTokTelegramSource
         * @description Exactly one source selector for Telegram delivery.
         *
         *     `url` performs or reuses extraction, `extraction_id` reuses recent extraction
         *     context, and `video_id` is accepted only for audio delivery.
         */
        TikTokTelegramSource: {
            /**
             * Url
             * @description TikTok URL to resolve and extract
             */
            url?: string | null;
            /**
             * Extraction Id
             * @description Recent extraction_id; avoids URL resolution and extraction
             */
            extraction_id?: string | null;
            /**
             * Video Id
             * @description Numeric TikTok post ID; only valid when delivery is audio
             */
            video_id?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthLive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveResponse"];
                };
            };
        };
    };
    getHealthReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description A required service credential is not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    extractTikTok: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TikTokExtractionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TikTokExtractionResponse"];
                };
            };
            /** @description Missing or invalid tt-scrap bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation or delivery-parameter error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Stable tt-scrap error envelope; inspect error.code */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    extractTikTokMusic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TikTokMusicRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TikTokMusicResponse"];
                };
            };
            /** @description Missing or invalid tt-scrap bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation or delivery-parameter error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Stable tt-scrap error envelope; inspect error.code */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deliverTikTokToTelegram: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TikTokTelegramDeliveryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramAPIResponse"] | components["schemas"]["TelegramMultiDeliveryResponse"];
                };
            };
            /** @description Some earlier Telegram album batches succeeded before a failure */
            207: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramMultiDeliveryResponse"];
                };
            };
            /** @description Missing or invalid tt-scrap bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation or delivery-parameter error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A raw Telegram Bot API failure or a stable tt-scrap error envelope. Do not automatically retry an ambiguous upload response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramAPIResponse"] | components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    extractInstagram: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstagramExtractionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstagramExtractionResponse"];
                };
            };
            /** @description Missing or invalid tt-scrap bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation or delivery-parameter error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Stable tt-scrap error envelope; inspect error.code */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    downloadAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resolved media bytes; Content-Type reflects the detected format */
            200: {
                headers: {
                    /** @description Exact response size in bytes */
                    "Content-Length"?: number;
                    /** @description Attachment filename with a detected-format extension */
                    "Content-Disposition"?: string;
                    /** @description Quoted SHA-256 digest */
                    ETag?: string;
                    /** @description Unquoted SHA-256 digest */
                    "X-Content-SHA256"?: string;
                    /** @description Always private, no-store */
                    "Cache-Control"?: string;
                    /** @description Request correlation identifier */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                    "video/mp4": string;
                    "audio/mpeg": string;
                    "audio/mp4": string;
                    "image/jpeg": string;
                    "image/png": string;
                    "image/webp": string;
                    "image/heic": string;
                    "image/heif": string;
                    "image/avif": string;
                    "image/tiff": string;
                    "image/bmp": string;
                    "image/gif": string;
                };
            };
            /** @description Missing or invalid tt-scrap bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation or delivery-parameter error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Stable tt-scrap error envelope; inspect error.code */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
