import { lstat, mkdir, readFile, symlink } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

// openapi-typescript 7.13 uses the TypeScript 5 compiler API. The application
// itself stays on TypeScript 7; give only the generator package a nested link
// to its compatible compiler alias before loading it.
const projectRoot = fileURLToPath(new URL("..", import.meta.url));
const compilerLink = join(projectRoot, "node_modules/openapi-typescript/node_modules/typescript");
try {
  await lstat(compilerLink);
} catch (error) {
  if (!(error instanceof Error) || !("code" in error) || error.code !== "ENOENT") throw error;
  await mkdir(dirname(compilerLink), { recursive: true });
  await symlink("../../typescript-openapi", compilerLink, "dir");
}

const generatorPackage = ["openapi", "typescript"].join("-");
const generator = await import(generatorPackage) as typeof import("openapi-typescript");
const { default: openapiTS, astToString } = generator;

let schema: unknown;
const schemaFile = Bun.env.TT_SCRAP_OPENAPI_FILE?.trim();
if (schemaFile) {
  schema = JSON.parse(await readFile(schemaFile, "utf8"));
} else {
  const baseUrl = (Bun.env.TT_SCRAP_BASE_URL || "http://127.0.0.1:8000").replace(/\/+$/, "");
  const response = await fetch(`${baseUrl}/openapi.json`);
  if (!response.ok) throw new Error(`Failed to fetch tt-scrap OpenAPI: HTTP ${response.status}`);
  schema = await response.json();
}
const ast = await openapiTS(schema as Parameters<typeof openapiTS>[0]);
const banner = "// Generated by scripts/generate-tt-scrap-types.ts. Do not edit manually.\n";
await Bun.write(new URL("../src/clients/tt-scrap.generated.ts", import.meta.url), banner + astToString(ast));
console.log("Updated src/clients/tt-scrap.generated.ts");
