name: Build and push Docker image

on:
  push:
    tags:
        - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Optional image tag to apply on manual runs (e.g., test or v1.2.3)'
        required: false
        type: string

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata (tags, labels)
        if: github.event_name == 'push'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Extract Docker metadata for manual run (tags, labels)
        if: github.event_name == 'workflow_dispatch'
        id: meta_manual
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # Use provided input tag if set
            type=raw,value=${{ github.event.inputs.tag }},enable=${{ github.event.inputs.tag != '' }}
            # Always add a short SHA tag
            type=sha,format=short
            # And a simple manual tag
            type=raw,value=manual

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push (tag push)
        if: github.event_name == 'push'
        id: push_tag
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push (manual)
        if: github.event_name == 'workflow_dispatch'
        id: push_manual
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta_manual.outputs.tags }}
          labels: ${{ steps.meta_manual.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate artifact attestation (tag push)
        if: github.event_name == 'push'
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push_tag.outputs.digest }}
          push-to-registry: true

      - name: Generate artifact attestation (manual)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push_manual.outputs.digest }}
          push-to-registry: true